print()

print(ur mom)

def railroad():
    penup()
    goto(-700,-400)
    pencolor("gray")
    width(10)
    setheading(90)
    forward(1000)
    penup()
    setheading(0)
    forward(100)
    setheading(270)
    pendown()
    forward(100)
    penup()
    goto(-700, -400)
    setheading(90)
    forward(30)
    penup()
    for i in range (0, 1000/50):
        setheading(0)
        back(30)
        pos = position()
        pendown()
        forward(130)
        penup()
        goto(pos)
        setheading(90)
        forward(50)
